# Generated by Django 3.1.5 on 2021-02-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrobamodel',
            name='description',
            field=models.CharField(default='nada', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrobamodel',
            name='name',
            field=models.CharField(default='nada1', max_length=200),
            preserve_default=False,
        ),
    ]
