# Generated by Django 3.1.5 on 2021-02-02 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_usuarios', '0002_auto_20210127_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrobamodel',
            name='last_query_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
